modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="ticc"
version="${file.jarVersion}"
displayName="TiCC"
authors="Chemiofitor(HLFT)"
[[dependencies.ticc]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ticc]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ticc]]
   modId="tconstruct"
   mandatory=true
   versionRange="[3.3.4,)"
   ordering="NONE"
   side="BOTH"

