modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="tconstruct_compatible"
version="${file.jarVersion}"
displayName="TConstruct Compatible"
authors="hlft"
description='''
A mod tool-lib.
'''
[[dependencies.tconstruct_compatible]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tconstruct_compatible]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tconstruct_compatible]]
    modId="tconstruct"
    mandatory=true
    versionRange="[1.16.5-3.2.0.290,)"
    ordering="AFTER"
    side="BOTH"
